# Generated by Django 4.1.5 on 2023-02-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='productuploadmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('des', models.CharField(max_length=500)),
                ('pimage', models.ImageField(upload_to='ecommerceapp/static')),
            ],
        ),
    ]
