# Generated by Django 4.1.5 on 2023-02-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0006_buymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='customerdetailsmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('cardno', models.CharField(max_length=30)),
                ('cardexpiry', models.CharField(max_length=30)),
                ('security', models.CharField(max_length=30)),
            ],
        ),
    ]
