# Generated by Django 4.1.5 on 2023-02-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0007_customerdetailsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='productuploadmodel',
            name='shopid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
